apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-app
    app.kubernetes.io/component: postgresql-demo-svc
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/part-of: demo-app
  name: postgresql-demo-svc
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql-demo
    deploymentconfig: postgresql-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}